spring:
  application:
    name: smart-booking

  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/smart_booking
    username: root
    password: tiger

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8080